services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: security_demo_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: security_db     # ← security_db 쓰고 싶으면 이렇게!
      POSTGRES_USER: pilot
      POSTGRES_PASSWORD: pilot1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
