version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: security_demo_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
